name: Postman CI - Departament-New

on:
  push:
    branches:
      - cgehlen
  pull_request:
    branches:
      - cgehlen

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Verificar versão do Newman e Node.js
    - name: Check version Newman and Node
      run: |
        newman --version
        node --version

    # Instalar newman-reporter-htmlextra
    - name: Install Newman-Reporter-HtmlExtra
      run: |
        sudo npm install -g newman-reporter-htmlextra

    # Executar a coleção com ambiente especificado
    - name: Execute collection
      run: |
        newman run postman/collections/Supernatural.postman_collection.json -e postman/collections/Supernatural.postman_environment.json -g postman/collections/super_globals.json --reporters cli,htmlextra --reporter-htmlextra-export postman/collections/docs/index.html

    # Carregar relatório de teste
    - name: Upload Test Report
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: postman/collections/docs/index.html
